### PR TITLE
Datatables only page number pagination

### PR DESCRIPTION
**Pull request by maysu1914**
Add an option to disable pagination if the format is other than 'datatables'.

#39

### CODE REVIEW

**Comment by izimobil** [comment]
Hi, thanks for your PR, can you please add some documentation in the relevant sections and tests please ? I'd like to keep 100% coverage. Thanks :)

**Comment by maysu1914** [comment]
I am getting errors while building the documentation

```
Running Sphinx v1.7.2

Sphinx error:
Builder name build not registered or available through entry point
```

**Comment by izimobil** [comment]
> I am getting errors while building the documentation
> 
> ```
> Running Sphinx v1.7.2
> 
> Sphinx error:
> Builder name build not registered or available through entry point
> ```

Are you doing:
`$ make build`

?

**Comment by maysu1914** [comment]
> > I am getting errors while building the documentation
> > ```
> > Running Sphinx v1.7.2
> > 
> > Sphinx error:
> > Builder name build not registered or available through entry point
> > ```
> 
> Hmm, can you try `make docs` or simply `make` instead ?

Still same. I couldn't get it to work. But 'make html' works fine.

**Comment by izimobil** [comment]
Merged, thanks for your work !

**Pull request merged**
