### PR TITLE
Make django-rest-framework-datatables works with POST requests

### PR DESCRIPTION
**Pull request by RicardoBPedro**
- Get datatables params from GET and POST method;

### CODE REVIEW

**Comment by RicardoBPedro** [comment]
@izimobil I believe that CI failed caused from some disk error because old versions of python don`t treat different the request data.
Is that possible to rerun travis?

**Comment by izimobil** [comment]
Hello !
I've finally fixed this in this commit https://github.com/izimobil/django-rest-framework-datatables/commit/50d0e894b5131aa464ae92ed15745e158b278d65, with docs and tests.
Thank you !

**Comment by clog-rocks** [comment]
@izimobil Amazing, thanks a lot! When could we expect pypi release? Keen to get it up and running.

**Comment by izimobil** [comment]
@clog-rocks Version 0.5.2 is published :)

**Comment by clog-rocks** [comment]
Awesome, great thanks! That was fast. I am, however, having problems setting it up. My API endpoint which is based on viewsets.ModelViewSet returns 403 when datatables has `ajax.type` set to `"POST"` as per documentation. Do I need to do anything on API side of things to get it to work?

**Comment by izimobil** [comment]
@clog-rocks In a ModelViewSet, POST is mapped to the create() method... you can overriding the create method to call the list() method for example.

**Comment by clog-rocks** [comment]
Thanks! I tried to do it like that:

    def create(self, request, *args, **kwargs):
        print("overriding create()")
        return self.list(self, request, args, kwargs)

but am still getting 403 and no `print()` is executed from `create()` above. So something must be happening before that.

**Comment by izimobil** [comment]
You must have permissions issues, I guess DRF checks the "<your_app>.add_<your_model>" permission before calling the create() method.

I've just tested this, and it works:
```python
    def create(self, request, *args, **kwargs):
        if request.GET.get('format') == 'datatables':
            return self.list(request)
        return super().create(request, *args, **kwargs)
```

**Comment by izimobil** [comment]
I think ModelViewSet is not ideal for using POST with DataTables anyway.

**Comment by clog-rocks** [comment]
In settings.py have `rest_framework.permissions.IsAuthenticated` as default for DRF permission classes and I am authenticated as other endpoints do work properly. I tried setting `permission_classes = ["rest_framework.permissions.AllowAny"]` in endpoints view class but still getting 403. Any clues where else could I look?

**Comment by CristopherH95** [comment]
> In settings.py have `rest_framework.permissions.IsAuthenticated` as default for DRF permission classes and I am authenticated as other endpoints do work properly. I tried setting `permission_classes = ["rest_framework.permissions.AllowAny"]` in endpoints view class but still getting 403. Any clues where else could I look?

Are you including Django's CSRF token in your POST request from the client? Typically Django will raise a 403 if you make a POST request without a CSRF token.

This would be similar to this in the AJAX config for DataTables:

```javascript
$("#mytable").dataTable({
    ajax: {
        url: "{% url 'my_endpoint' %}",
        type: "POST",
        beforeSend: function(xhr) {
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
    },
});
```

**Comment by clog-rocks** [comment]
@CristopherH95 Thanks Chris, missing CSRF token was the problem. Got it all nicely working now. Great thanks!

**Pull request closed without merging**
