### PR TITLE
Dependency version updates

### PR DESCRIPTION
**Pull request by matthewhegarty**
The existing dependencies referenced django versions which are now past [end of life](https://endoflife.date/django).

- Have updated dependencies to remove reference to EOL packages
- Have replaced deprecated `assertEquals()` calls with `assertEqual()`

### CODE REVIEW

**Comment by izimobil** [comment]
Hi @matthewhegarty , thanks for this ! could you also update README.rst (python badge and requirements section) ?

**Comment by matthewhegarty** [comment]
I modified the readme text to match that on [DRF homepage](https://www.django-rest-framework.org/).  I hope that's ok.

The badge should be updated when the next PyPI release occurs.

**Comment by izimobil** [comment]
> I modified the readme text to match that on [DRF homepage](https://www.django-rest-framework.org/). I hope that's ok.
> 
> The badge should be updated when the next PyPI release occurs.

OK thanks ! I was talking about the Python badge that should be updated with 3.10 version, I think we could also include 3.11 in tox.ini, what do you think ?

**Comment by matthewhegarty** [comment]
>  I was talking about the Python badge that should be updated with 3.10 version

You mean the [shields.io badges](https://img.shields.io/pypi/pyversions/djangorestframework-datatables.svg)?  If so, these will be updated when the project is built.  I think they get drawn from `setup.cfg` which has been updated with the correct python versions.  Let me know if I've misunderstood something here.

> I think we could also include 3.11 in tox.ini

Done

I also modified the tox.ini command so that deprecation warnings are included (this also meant an update to settings.py).

**Comment by matthewhegarty** [comment]
Hi David - is this ok to merge now?

**Comment by izimobil** [comment]
Hi @matthewhegarty sorry for the delay, merged ! thanks.

**Pull request merged**
